### ISSUE TITLE
install mobileUi error [node v8,node v9.node v10 , node v11]

### ISSUE THREAD

**Issue by atmanegara** [MobileUI/mobileui#12]
node v8
![gambar](https://user-images.githubusercontent.com/9096711/111023933-ecaf7200-8416-11eb-9801-d4b516c47b9e.png)

node v9
![gambar](https://user-images.githubusercontent.com/9096711/111023998-3ef09300-8417-11eb-9b09-9718193c9b9f.png)

node v10
![gambar](https://user-images.githubusercontent.com/9096711/111024051-870fb580-8417-11eb-9e53-47cfd06a03fd.png)

node v11
![gambar](https://user-images.githubusercontent.com/9096711/111024071-af97af80-8417-11eb-84be-c118dc473bf0.png)

**Comment by webb24h** [comment]
Either decrease nodejs to a previous version or use a different framework. 

Similar frameworks :
Onsen - https://onsen.io/
Framework7 - https://framework7.io/

**Comment by peppos80** [comment]
I have the same problem too! has anyone solved it? :-(

**Comment by T-Ev** [comment]
See solution here:
https://github.com/MobileUI/mobileui/issues/13#issuecomment-1339956903

**Comment by fabiorogeriosj** [comment]
I solved it, updated the libs! New life!
