### ISSUE TITLE
Mobileui installation error

### ISSUE THREAD

**Issue by webb24h** [MobileUI/mobileui#13]
What version of nodejs works with mobileui? Can't seem to be able to install the framework anymore. 

<pre><span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> har-validator@5.1.5: this library is no longer supported
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> natives@1.1.6: This module relies on Node.js&apos;s internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
</pre>

**Comment by fabiorogeriosj** [comment]
Hi, this mobule need update, I'll make this

**Comment by peppos80** [comment]
I have the same problem too! has anyone solved it?

**Comment by webb24h** [comment]
> Hi, this mobule need update, I'll make this

Thank you for your hard work. Mobileui is such a great framework you know? It's easier than the other design frameworks. I have a question. I have a cordova app that was completely created with mobileui before it stopped working. I'm able to use the app functionalities and functions within the browser quite well. But when I build the app for ios, `openPage()` function does not work in the iphone simulator. Do you know how to fix this?

This will not open the page in ios simulator (nothing happens)
```
<button id="openPageLogin" class="button welcomeScreenBtn">LOGIN</button>
document.getElementById('openPageLogin').addEventListener('touchstart', function() { openPage('login') }, false);
```

**Comment by atmanegara** [comment]
> npm install -g git://github.com/T-Ev/mobileui#1.1.21

yes, thank's solved

**Comment by fabiorogeriosj** [comment]
I solved it, updated the libs! New life!
