### ISSUE TITLE
Things i want to do for the mobileui

### ISSUE THREAD

**Issue by dotenorio** [MobileUI/mobileui#3]
- purple-300 doesn't work
- put full link on mobileui preview command:

```
$ mobileui preview
 RUNNING:  Server for preview app running on http://localhost:8080
For stop this server hit Ctrl+C.
```
- create alias to mobileui preview, for example: 

```
$ mui p
```

- create auxiliar height class to use with vertical-align-*

**Comment by dotenorio** [comment]
Done!!

[Fixes and Improvements](https://github.com/MobileUI/components/pull/80)
[fix: att doc with .full-height class ](https://github.com/MobileUI/mobileui.github.io/pull/6)
[feat: add uri on preview log to use Alt+click ](https://github.com/MobileUI/mobileui/pull/4)

_obs.: the item `create alias to mobileui preview` i'll don't do it, unnecessary._

**Comment by fabiorogeriosj** [comment]
Thanks @dotenorio

**Comment by dotenorio** [comment]
We're welcome.

I really love MobileUI ❤️
